version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fabrica_testing
    ports:
      - 3306:3306

  app:
    build:
      context: .
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql   # Usamos el nombre del servicio de MySQL
      DB_PORT: 3306
      DB_DATABASE: fabrica_testing
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - mysql
    ports:
      - "80:80"

