name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-ci-cd:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Configurar PHP y dependencias
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, xml, bcmath, zip

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # 3. Configurar el entorno
    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    # 4. Ejecutar migraciones y pruebas
    - name: Run Migrations
      run: php artisan migrate --env=testing --no-interaction --force

    - name: Run Tests
      run: php artisan test --env=testing

    # 5. Empaquetar aplicación
    - name: Package Application
      run: zip -r laravel_app.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: laravel_app
        path: laravel_app.zip

    # 6. Construir imagen Docker
    - name: Build Docker Image
      run: docker build -t laravel-app:latest .

    # 7. Desplegar imagen Docker localmente
    - name: Run Docker Container
      run: |
        docker run -d -p 8080:80 --name laravel-app laravel-app:latest
