name: Laravel CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Configurar el entorno
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, pdo, xml, bcmath, zip
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate --env=testing --no-interaction --force

    - name: Run Tests
      run: php artisan test --env=testing

    # Opcional: Verificar estilo de código
    - name: Run PHP-CS-Fixer
      run: composer run cs-fix
